server:
  port: 0

spring:
  application:
    name: post-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social_media
    username: postgres
    password: 1954623790

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
