spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social_media
    username: postgres
    password: 1954623790
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  # 32-bit secret key
  access-token-key: '{"kty": "oct", "k": "3eb97465e14c1dafb0f287da7651b683272a4bf7d802dc46a8c1c8fa2386fcea"}'
  # 16-bit secret key
  refresh-token-key: '{"kty": "oct", "k": "d4434ef0590e8335919ebb0de4d6068c"}'
  #  m - minutes
  #  h - hours
  #  d - days
  access-token-expiration: "15m"
  refresh-token-expiration: "30d"

logging:
  level:
    org.springframework.security: trace
